# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ v4, v3 ]
  pull_request:
    branches: [ v4, v3 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global url."https://".insteadOf git://
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - run: |
          sudo apt-get update
          sudo apt-get install python2 libgl1-mesa-dev libglew-dev libglfw3 libglfw3-dev libxxf86vm-dev
          python download-deps.py --r no
          echo -e "y" | bash install-deps-linux.sh
          cmake -B b -S .
          cmake --build b

  windows-2019:
    runs-on: windows-2019
    steps:
      - run: git config --global url."https://".insteadOf git://
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - run: python download-deps.py --r no
      - run: cmake -B b -S . -G "Visual Studio 16 2019" -A Win32
      - run: cmake --build b

  windows-2022:
    runs-on: windows-2022
    steps:
      - run: git config --global url."https://".insteadOf git://
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - run: python download-deps.py --r no
      - run: cmake -B b -S . -G "Visual Studio 17 2022" -A Win32
      - run: cmake --build b

  macos-latest:
    runs-on: macos-latest
    steps:
      - run: git config --global url."https://".insteadOf git://
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - run: |
          # MacOS Monterey 12.3 no longer has Python 2.7 installed by default!
          set -x
          brew install pyenv
          pyenv install 2.7.18
          pyenv global 2.7.18
          echo "${HOME}/.pyenv/shims" >> $GITHUB_PATH
          pip install --upgrade setuptools
          python download-deps.py --r no
          cmake -B b -S . -GXcode
          cmake --build b

  macos-latest_ios:
    runs-on: macos-latest
    steps:
      - run: git config --global url."https://".insteadOf git://
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - run: |
          # MacOS Monterey 12.3 no longer has Python 2.7 installed by default!
          set -x
          brew install pyenv
          pyenv install 2.7.18
          pyenv global 2.7.18
          echo "${HOME}/.pyenv/shims" >> $GITHUB_PATH
          pip install --upgrade setuptools
          python download-deps.py --r no
          cmake -B b -S . -GXcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_SYSROOT=iphonesimulator
          cmake --build b --config Release --target cpp-tests -- -quiet -destination "platform=iOS Simulator,name=iPhone Retina (4-inch)"

  windows-2019-android:
    runs-on: windows-2019
    steps:
      - run: git config --global url."https://".insteadOf git://
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: python download-deps.py --r no
      - run: |
          export ANDROID_NDK=${ANDROID_NDK_ROOT}
          export NDK_ROOT=${ANDROID_NDK_ROOT}
          ./gradlew assembleRelease -PPROP_BUILD_TYPE=cmake --info
        shell: bash
        working-directory: tests/cpp-tests/proj.android

  ubuntu-latest-android:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global url."https://".insteadOf git://
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: |
          sudo apt-get update
          sudo apt-get install python2
          python download-deps.py --r no
      - run: |
          export ANDROID_NDK=${ANDROID_NDK_ROOT}
          export NDK_ROOT=${ANDROID_NDK_ROOT}
          ./gradlew assembleRelease -PPROP_BUILD_TYPE=cmake --info
        shell: bash
        working-directory: tests/cpp-tests/proj.android
